version: '3.9'
services:
  auth_1:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8021

  auth_2:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8022

  auth_3:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8023

  auth_4:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8024

  simple_broker_1:
    image: simple-broker
    network_mode: 'host'
    depends_on:
      - auth_1
    environment:
      - NODE_PORT=3161
      - AUTH_PORT=8021
      - RPCNODE_PORT=8545

  simple_broker_2:
    image: simple-broker
    network_mode: 'host'
    depends_on:
      - auth_2
    environment:
      - NODE_PORT=3162
      - AUTH_PORT=8022
      - RPCNODE_PORT=8545

  simple_broker_3:
    image: simple-broker
    network_mode: 'host'
    depends_on:
      - auth_3
    environment:
      - NODE_PORT=3163
      - AUTH_PORT=8023
      - RPCNODE_PORT=8545

  simple_broker_4:
    image: simple-broker
    network_mode: 'host'
    depends_on:
      - auth_4
    environment:
      - NODE_PORT=3164
      - AUTH_PORT=8024
      - RPCNODE_PORT=8545
