version: '3.9'
services:
  auth_1:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8021

  auth_2:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8022

  auth_3:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8023

  auth_4:
    image: miker83z/umbral-rs-web-service:latest
    network_mode: 'host'
    environment:
      - AUTH_API_PORT=8024
